version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - SECRET_KEY
    command: ./utils/startup.sh
    volumes:
      - .:/code
      - ./docker_utils/web:/code/utils
    ports:
      - "8000:8000"
    depends_on:
      - db