"""
WSGI config for Vote Predict project.

It exposes the WSGI callable as a module-level variable named ``application``.

Generated by Django 3
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "votepredictbackend.settings")

application = get_wsgi_application()
